requires:
- category: "layer"
  name: "gentoo-portage"
  version: ">=0"
steps:
- cp -rf package.use /etc/portage/
- cp -rf make.conf /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.license /etc/portage/
